"""
FILE: main.py
PURPOSE: Application entry point — creates the FastAPI app and wires everything together.

HOW FASTAPI WORKS:
  1. We create an 'app' object (the web application).
  2. We include our router (which has all the endpoints).
  3. When uvicorn runs this file, it starts an HTTP server listening on a port.

WHAT IS uvicorn?
  uvicorn is an ASGI server — it handles incoming HTTP connections and
  calls our FastAPI app to process each request.
  Run with:  uvicorn main:app --reload
    - main     = this file (main.py)
    - app      = the FastAPI() object defined below
    - --reload = auto-restart when code changes (dev mode only)
"""

from fastapi import FastAPI

# Import the router that contains all our task endpoints
from app.routes import router

# -----------------------------------------------------------------------
# Create the FastAPI application
# -----------------------------------------------------------------------
app = FastAPI(
    title="Task Manager API",
    description=(
        "A simple REST API for managing tasks. "
        "Built with FastAPI to demonstrate a full CI/CD pipeline."
    ),
    version="1.0.0",
    # Interactive docs available at /docs (Swagger UI) and /redoc
)

# -----------------------------------------------------------------------
# Register routers
# -----------------------------------------------------------------------
# include_router attaches all routes defined in routes.py to our main app.
# prefix="" means routes use their paths as-is (e.g., /tasks, /health).
app.include_router(router)


# -----------------------------------------------------------------------
# Root endpoint
# -----------------------------------------------------------------------
@app.get("/", summary="Root", description="API welcome message and links to docs.")
def root() -> dict[str, str]:
    """
    GET / — Returns a welcome message with links to the API documentation.
    The interactive Swagger docs are auto-generated by FastAPI at /docs.
    """
    return {
        "message": "Task Manager API is running",
        "docs": "/docs",
        "health": "/health",
    }
